### ISSUE TITLE
working on Makefile

### ISSUE THREAD

**Issue by Jay4869** [berkeley-stat159/project-iota#104]
@amandazhang  Please give me the full command for download the new datasets

**Comment by amandazhang** [comment]
wget -r --no-parent --reject="index.html*" -e robots=off https://nipy.bic.berkeley.edu/rcsds/ds115/sub001/ --no-check-certificate

cp -r nipy.bic.berkeley.edu/rcsds/ds115/sub001/model/model001 sub001/
rm -rf nipy.bic.berkeley.edu/

**Comment by Jay4869** [comment]
example: `data/sub001/BOLD/' + f1 + '/filtered_func_data_mni.nii.gz'`
and `f1` will be users input like `task001_run001`

**Comment by amandazhang** [comment]
OKAY,then please add the following command after what i've written above:

cp -r task001_run001.feat  task001_run001/
cp -r task002_run001.feat  task002_run001/
cp -r task003_run001.feat  task003_run001/
rm -rf  task001_run001.feat
rm -rf  task002_run001.feat
rm -rf  task003_run001.feat

**Comment by Jay4869** [comment]
It is done!
