### ISSUE TITLE
make dataset doesn't work

### ISSUE THREAD

**Issue by rossbar** [berkeley-stat159/project-iota#142]
When I run make dataset, I get the following error (I'm working remotely so I had to use a screen grab, sorry for the poor quality):

![iota_error](https://cloud.githubusercontent.com/assets/1268991/11833935/92e459b4-a37c-11e5-86cd-3f889e664244.png)

Please push fixes ASAP. If you are not planning to fix this, apply the **wontfix** label to this issue and we will proceed manually

**Comment by Jay4869** [comment]
<img width="442" alt="_20151215224606" src="https://cloud.githubusercontent.com/assets/8618777/11834082/e8726000-a37d-11e5-880e-624de2efa44b.png">

@rossbar I did the same code in VM, but it works to me, but I will take careful look on it

**Comment by rossbar** [comment]
I did not run the `mv` command, it was part of the `make dataset` call. Can you verify that `make dataset` works from a clean build? In other words, if you clone your project into a new, empty directory and try to run `make dataset` is it successful?

**Comment by Jay4869** [comment]
we are working on it

2015-12-15 23:39 GMT-08:00 Ross Barnowski <notifications@github.com>:

**Comment by rossbar** [comment]
Any progress? Let me know how much longer you expect to work on it. I'd like to be able to start grading ASAP

**Comment by Jay4869** [comment]
We already fixed it, so it should be worked, but if it still doesn't work,
please proceed and fix it for us please

Thanks in advanced
Team-iota

**Comment by rossbar** [comment]
When I pulled there were no new additions. I still get errors when trying to download the data:

```
make dataset cd data && make
make[1]: Entering directory `/media/ross/DATAPART1/stats159/projects/project-iota/data'
wget http://openfmri.s3.amazonaws.com/tarballs/ds115_sub001-005.tgz
--2015-12-17 16:23:05--  http://openfmri.s3.amazonaws.com/tarballs/ds115_sub001-005.tgz
Resolving openfmri.s3.amazonaws.com (openfmri.s3.amazonaws.com)... 54.231.49.88
Connecting to openfmri.s3.amazonaws.com (openfmri.s3.amazonaws.com)|54.231.49.88|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4513139859 (4.2G) [application/x-tar]
Saving to: ‘ds115_sub001-005.tgz.1’

100%[====================================>] 4,513,139,859 24.5MB/s   in 2m 11s 

2015-12-17 16:25:16 (33.0 MB/s) - ‘ds115_sub001-005.tgz.1’ saved [4513139859/4513139859]

tar -xvzf ds115_sub001-005.tgz sub001
sub001/
sub001/BOLD/
sub001/BOLD/task001_run001/
sub001/BOLD/task001_run001/bold.nii.gz

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
make[1]: *** [data] Error 2
make[1]: Leaving directory `/media/ross/DATAPART1/stats159/projects/project-iota/data'
make: *** [dataset] Error 2
```

**Comment by rossbar** [comment]
Note that this was after a fresh clone of the project

**Comment by Jay4869** [comment]
@rossbar  I have already fixed it and I ran the couple times on the SAVIO which is school server. If you still have trouble to `make`, please let know I would like to stop by your office tmr

Best

**Comment by rossbar** [comment]
I was able to re-clone the project and successfully run the build/analysis chain. Thanks for taking the time to work this out :+1:

**Comment by Jay4869** [comment]
That is a good news to me. Thank you for giving us time to fix those

2015-12-18 7:15 GMT-08:00 Ross Barnowski notifications@github.com:
