### ISSUE TITLE
No data in cond007

### ISSUE THREAD

**Issue by Jay4869** [berkeley-stat159/project-iota#28]
@lizeyuyuz  Could you please double check file `cond007`? I didn't see any date in it, but if maybe happen missing when I decompressed the `sub001` file

**Comment by lizeyuyuz** [comment]
@Jay4869 Yes I've checked before, 007is empty

**Comment by Jay4869** [comment]
Do we just ignore it?

**Comment by lizeyuyuz** [comment]
@Jay4869 If there's nothing in it, we don't get anything out of it, no matter what we do about it. I'd say just ignore it.

**Comment by Jay4869** [comment]
i am clear!
