### ISSUE TITLE
Improve P-value map and check linear modeling normality

### ISSUE THREAD

**Issue by Jay4869** [berkeley-stat159/project-iota#49]
1. There is a simply way you can approach that try to make a small rectangle to mark our significant sub-area in red
Here is link should be useful
http://matplotlib.org/1.5.0/examples/shapes_and_collections/artist_reference.html

2. Trying to do a basic normality test like QQ-plot and we see how the result looks like

**Comment by amandazhang** [comment]
Thanks for the link!

**Comment by Jay4869** [comment]
The biggest idea is producing out the result which is simply and clear because the big chunk grade is everything is worked out!
Thanks for your work

**Comment by Jay4869** [comment]
https://piazza.com/class/id3duvdb9wt1ge?cid=156

**Comment by Jay4869** [comment]
It is done so far!
