### ISSUE TITLE
working on linear modeling

### ISSUE THREAD

**Issue by Jay4869** [berkeley-stat159/project-iota#57]
Re-working on the linear modeling because we generated new convo-response

1. Only doing simple regression on the block test `cond005`, and figure out the difference between 2-black and 0-black, which shows how the long term memory works in the brain. 
Looking for what result is

2. Adding block test and contrast test `cond003` in the linear regression and apply hypothesis test to check how the betas work, and make p-value map for selecting sub-region of brain

**Comment by Jay4869** [comment]
@matthew-brett For the simple regression on the block test, I think I also need to add start and end instruction `cond001` and `cond004`, is that correct? I just want to double check

**Comment by matthew-brett** [comment]
You can add these, if you like, but I suspect they won't change the result very much.   The general idea should be to add regressors that you believe may explain variance, and then test to see if they do explain a large amount of variance.  In this case, you'd have to look, but I suspect they would have rather small influence compared to the block regressor.

**Comment by Jay4869** [comment]
done!
