### ISSUE TITLE
Compare 0back and 2back task

### ISSUE THREAD

**Issue by lizeyuyuz** [berkeley-stat159/project-iota#68]
Based on the linear model we have, we have found the estimated betas for each voxel for each task level: 0back, 1back, 2back .

For subject 1 with schizophrenia:
```
y0  =  X0* \beta0 + u0
1back: 
y1  =  X1* \beta1 + u1
2back: 
y2  =  X2* \beta2 + u2
```

Next we want to compare 0back and 2back task and see how brain reacts differently, but we need some help on starting this. 

Our idea is a t-test between the estimated betas for each task, so if a p-value is very small for specific voxels, then these are the voxels that are activated to remember the previous two letters. But our concern is that the design matrices, X0 and X2 are different, is it still possible to compare the estimated betas?

**Comment by matthew-brett** [comment]
You can subtract the betas, as long as the regressors are comparable.  I mean that, you have used the same convolution preparing both regressors, and in the neural input 1 unit in the first run (the 0 back) is equivalent to 1 unit in the second run (the 2 back).   This would be the case if you used the simple neural time course algorithm we used in class.

Now you need the denominator for the t-statistic, where the numerator is `\beta_2 - \beta_1`.  The easiest way to get this, is to make a new 'block diagonal' design containing the design for run 1 in the top left hand corner, with zeros to the right and below, and the design for run 2 in the bottom right hand corner, with zeros to the left and zeros above.  The data would then be the (time by voxels) for run 1 stacked on top of (`vstack`) the (time by voxels) for run 2.

When you estimate this, you can get the numerator by a contrast subtracting the beta in the first column corresponding to the first run from the beta in the first column corresponding to the second run.  The denominator follows from the formula in the GLM page from class.  In this case you are comparing `\beta2 - \beta2` to the residual variance pooled across both runs.

**Comment by Jay4869** [comment]
I will take look tmr!
Could you please assign it to me?
