### ISSUE TITLE
Identifying the region for time series analysis

### ISSUE THREAD

**Issue by lizeyuyuz** [berkeley-stat159/project-iota#69]
As you can see from the picture, We have found the threshold -log10(p-values) and we identified voxels of activation. To do time series analysis, we want to identify this activation site base on these voxels, so that we can sample from this region, and see how they change over time. 

![thresholded_p_values5](https://cloud.githubusercontent.com/assets/12566149/11487020/6e25d448-9771-11e5-80de-475a6def2f8a.png)

Can you help us identify these regions?

**Comment by matthew-brett** [comment]
Sorry to be slow to get back to you.

I'm not quite sure what you're asking - do you want a name for this region?  

Or - you want to find the voxel coordinate for this region?
