### ISSUE TITLE
Final report draft feedback

### ISSUE THREAD

**Issue by rossbar** [berkeley-stat159/project-iota#73]
- You refer to "blood pressure" as your data: I think you mean BOLD signal,
   which is blood oxygen level, not blood pressure
 - section 3.1 - to me, it is not so necessary to spend so much time discussing
   the mathematics behind the GLM, as it has been covered extensively in class
   and in readings. Instead, you should focus on the application of linear 
   modelling to your data specifically: show the design matrix, describe your
   regressors, etc. 
 - data preprocessing doesn't belong in the results section
 - There is no analysis in your paper to provide feedback on.

**Comment by amandazhang** [comment]
@rossbar  Hi Ross, I believe your comments are for report file in paper folder. Actually that was still the old version of what we had done when we did presentation last time in class. Now we've done much more data processing and analyzing part, some of them are written in our Slides/progress file, but we haven't add those latest analysis in our final report part. Thanks for your feedback, we would make changes based on these comments.

**Comment by rossbar** [comment]
You don't need to worry as the drafts aren't graded; the feedback was solely for your benefit. If you want feedback on the analysis you've done, I strongly encourage you to get it into the draft and notify Jarrod and Matthew with @-mentions so they can pull again. If you're lucky, you can get it in there before they provide feedback on the drafts. There's no need to do this of course, especially since you got feedback today (presumably on your most recent results).
