### ISSUE TITLE
Need help on coverage

### ISSUE THREAD

**Issue by Jay4869** [berkeley-stat159/project-iota#83]
Ross, could you help us how to fix coverage because we get fails on coverage, please

**Comment by rossbar** [comment]
I don't see any failures... if you run `make coverage` you'll get your coverage report: to me yours is fine, you have 100% coverage on 3 files and 94% on a fourth

**Comment by Jay4869** [comment]
https://travis-ci.org/berkeley-stat159/project-iota/jobs/95266759

could you check it for me please

**Comment by Jay4869** [comment]
Fixed!
