### ISSUE TITLE
Check failed when pull request

### ISSUE THREAD

**Issue by ay2456** [berkeley-stat159/project-iota#86]
Hi Ross,

I was trying to create pull request for two .py file but 1 check failed.

https://travis-ci.org/berkeley-stat159/project-iota/builds/95469124

What should I do with that?

**Comment by rossbar** [comment]
There seem to be two separate issues:

1) TravisCI can't find nibabel. Is it in your requirements.txt?

2) The import of your f_test code failed. Check to see why this is. You can run `make coverage` on your local machine to see if you get the same error.

**Comment by ay2456** [comment]
I got it. Thanks!
